### ISSUE TITLE
It'd be nice if base64 encoded images were visible.

### ISSUE THREAD

**Issue by xori** [kpcyrd/ipfs.ink#4]
Example: https://ipfs.ink/e/Qmf9u4MuVh5gAEDL5wFq5G1Ln7QEXwz6V21tgNFmBWUxrc

There is an image tag under the title with a base64 encoded image. However because of the chosen CSP data urls are not allowed.

(current CSP response header: content-security-policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; **img-src https:**; form-action 'self';)

Is this intentional?

**Comment by kpcyrd** [comment]
hey @xori :)

This is sort of intentional, I just didn't think about this usecase yet. I've adjusted the csp to allow `img-src https: data:` and your image is now displayed correctly. I've noticed the image is slightly overflowing the container, I'm going to deploy a new version in some hours that resolves this issue as well.

Thanks for reporting this!

**Comment by xori** [comment]
And thank you for fixing! 👍
